# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('how_many', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('likes', models.IntegerField()),
                ('level', models.CharField(max_length=50)),
                ('instruction', models.CharField(max_length=100000)),
                ('dish_photo', models.CharField(max_length=10000)),
            ],
        ),
    ]
