# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 06:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ManyToManyField(blank=True, to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='quantity',
            name='ingredient',
            field=models.ManyToManyField(blank=True, to='recipes.Ingredient'),
        ),
        migrations.AddField(
            model_name='quantity',
            name='recipe',
            field=models.ManyToManyField(blank=True, to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='users.Profile'),
        ),
    ]
