# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20170816_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='how_many',
        ),
        migrations.AddField(
            model_name='quantity',
            name='ingredient',
            field=models.ManyToManyField(to='recipes.Ingredient'),
        ),
    ]
