# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20170820_0156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
                ('recipe', models.ManyToManyField(to='recipes.Recipe')),
            ],
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='ingredient',
        ),
        migrations.DeleteModel(
            name='Quantity',
        ),
    ]
