# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20170820_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('ingredient', models.ManyToManyField(to='recipes.Ingredient')),
                ('recipe', models.ManyToManyField(to='recipes.Recipe')),
            ],
        ),
        migrations.RemoveField(
            model_name='unit',
            name='value',
        ),
        migrations.AddField(
            model_name='unit',
            name='ingredient',
            field=models.ManyToManyField(to='recipes.Ingredient'),
        ),
    ]
