# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20170820_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='recipe',
            field=models.ManyToManyField(blank=True, to='recipes.Recipe'),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='ingredient',
            field=models.ManyToManyField(blank=True, to='recipes.Ingredient'),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='recipe',
            field=models.ManyToManyField(blank=True, to='recipes.Recipe'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='ingredient',
            field=models.ManyToManyField(blank=True, to='recipes.Ingredient'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='recipe',
            field=models.ManyToManyField(blank=True, to='recipes.Recipe'),
        ),
    ]
