# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20170901_1014'),
        ('recipes', '0007_auto_20170901_1529'),
    ]

    operations = [
    ]
